### ISSUE TITLE
Occasional performance spikes in SetEvent

### ISSUE THREAD

**Issue by jspohr** [dougbinks/enkiTS#11]
Using Microprofile on Windows, I noticed that `SetEvent `can occasionally take longer than usual. enkiTS calls it to wake up the worker threads in `AddTaskSetToPipe`.
`SetEvent `usually blocks for less than 1ms, but I've seen spikes way up in the 20s of ms, which is a problem if the game waits on a task which is blocked by `AddTaskSetToPipe`. It ends up producing noticable frame spikes every few seconds.
By changing the Event Object to auto-reset in `EventCreate `(https://msdn.microsoft.com/en-us/library/windows/desktop/ms682655(v=vs.85).aspx) these spikes disappear. However, this will only wake up 1 thread at a time, and may decrease thread utilization.
I could also avoid the issue by increasing the spin count, however this of course increases power consumption.
This is probably not a big issue if the threads rarely wait, so it depends on the workload of the scheduler, as well as the number of cores in use. Maybe auto-reset mode should be an option?

**Comment by dougbinks** [comment]
I've not observed this taking 20s of ms, but will take a look at this in a few days time.

I'm not sure that this is relevant, but what CPU are you using?

**Comment by dougbinks** [comment]
I've added a branch which uses semaphores instead of events, see:

https://github.com/dougbinks/enkiTS/commit/4766b360265b1fe185be82a319f07d49c2937970

This works on my system, and I'd be interested to know if it helps resolve the spikes you are seeing. If so I may switch the implementation to using this approach.

**Comment by dougbinks** [comment]
Note that one possibility for your issue is that it is not the call to SetEvent which is causing the spike, but oversubscription of threads causing the main thread to be context switched out. This would account for why the auto-reset SetEvent resolves the spike, as with only one thread woken you may not get oversubscription.

You can control the number of threads for the task scheduler at initialization, perhaps setting to GetNumHardwareThreads()-1 to see if you remove the spikes this way.

**Comment by jspohr** [comment]
Thanks for looking into this!

> I'm not sure that this is relevant, but what CPU are you using?
I've seen it happen on a Core i7 with HT using 8 threads, and on a Core i5 with 4 threads. The Core i7 runs under Windows 7, while the i5 is in a Windows 10 machine.

> I've added a branch which uses semaphores instead of events
Very interesting, I'll give it a go. Thanks for that.

> Note that one possibility for your issue is that it is not the call to SetEvent which is causing the spike, but oversubscription of threads causing the main thread to be context switched out. 
I thought about the possibility, and experimented with the number of threads. And it actually helps to reduce the number of threads on the Core i7. The spikes disappear if I use less than 3 threads. On the Core i5, I had no such luck, I saw it drop frames even with only 2 threads. So I concluded that I could rule out oversubscription.
One more thing I noticed was that if I went crazy with the number of threads, and ran 16 of them on the Core i7, my machine almost froze, it was nearly impossible to even move the mouse cursor. The actual load put on the scheduler was the same in all cases.

**Comment by jspohr** [comment]
I did some quick and dirty measurements with the semaphore implementation on the Core i7 using 8 threads.

The average frame takes about 7.1ms (v-sync off). ReleaseSemaphore takes about 0.02ms on average, with rare spikes of about 1ms. Task manager says CPU usage is at 35-45%.
Using the auto-reset event object, the performance is slightly better: average frame takes about 6.8ms, SetEvent takes 0.03ms on average, largest spike 1.5ms. CPU usage is about 25%. SetEvent is faster than ReleaseSemaphore most of the time. However, the semaphore is much less "spikey", which is my subjective impression from looking at Microprofile's "Spike %" value. I didn't do any thorough measurements.

Neither implementation causes any frame drops, so I'm happy with both of them. I'm leaning towards the semaphore, just because I use them in other places, too, and they seem to be more even in performance.

**Comment by dougbinks** [comment]
Glad you had a chance to look a the semaphore implementation. Does this work better than the original implementation?

Note that I based this off the dev branch which has a number of additions so will be slightly slower than the master branch, apologies. If you want a proper comparison just take the changes from Threads.h

> Neither implementation causes any frame drops, so I'm happy with both of them. I'm leaning towards the semaphore, just because I use them in other places, too, and they seem to be more even in performance.

The auto-reset event object will only wake one thread, so this would result in poor utilisation since it's likely the other task threads will be asleep. I did try an auto-reset event object where each thread which wakes up wakes other threads in turn, but in my tests this was poorer performing. If you'd like to try that version I've uploaded it to the branch dev_autoreset with this commit: https://github.com/dougbinks/enkiTS/commit/3f278c470c9e9e3c512feccd1bddc1299bc3895b

**Comment by jspohr** [comment]
> Glad you had a chance to look a the semaphore implementation. Does this work better than the original implementation?
It depends on the use case, IMO. I'm trying to achieve smooth 60 FPS gameplay, so consistent latency is more important to me than highest throughput. From my short evaluation of the semaphore implementation, it seems a better fit for me. For others, the original implementation with a manual reset event object might be better, although the oversubscription problem has me worried a bit.
There's this game console with a Windows-like OS, where the manual reset works totally fine. So there's probably no overall best implementation. I'd suggest to have a configuration option which allows to switch between implementations and profile which one works best.

**Comment by dougbinks** [comment]
I'd rather not maintain multiple implementations, so if the semaphore implementation works for you I'll move to this as it works well for me.

My own game project is an FPS, so stable frame times are also highly important. As yet I've not seen the original issue you observed, but the semaphore approach works equally well in my tests so I'm happy to switch to that.

**Comment by jspohr** [comment]
Of course, I made that suggestion because I though you'd want to keep the original implementation. Semaphore it is :)

**Comment by jspohr** [comment]
Avoyd looks spectacular, by the way :)
Kudos!

**Comment by dougbinks** [comment]
Thanks!

I've merged the change to master branch, along with new grainsize functionality.

Note that I'm experimenting with some changes for added performance if you're submitting many tasksets in a loop, hopefully I'll have that available by next week along with the 'pinned tasks' (tasks pinned to a given thread) functionality.

You've indicated that this brings the spikes you're seeing down to 1ms from ~20ms so I'll close this issue, but do feel free to re-open it if the solution isn't good.
