### ISSUE TITLE
Deadlock with WaitForNewPinnedTasks and WaitforAllAndShutdown

### ISSUE THREAD

**Issue by spnda** [dougbinks/enkiTS#128]
Running the `WaitForNewPinnedTasks` example deadlocks within `TaskScheduler::WaitforAll` at the end when calling `WaitforAllAndShutdown`, since the pinned task thread will continue to run, as `g_TS.GetIsRunning` won't return false. The pinned task thread will then just continue to loop its function and the `WaitforAll` will never return, since that thread will report that it's doing something.

**Comment by dougbinks** [comment]
Thanks for the report - I'll take a look shortly.

**Comment by spnda** [comment]
I just noticed that the `GetIsRunning` function is deprecated and that `GetIsShutdownRequested` should be used instead. I guess the example should be updated and the documentation made clear that the other function should not be used. Also, perhaps it should be marked `[[deprecated]]` to make it more clear that it is deprecated since I didn't notice until reading the documentation by accident.

**Comment by dougbinks** [comment]
I think the best option might be to make `GetIsRunning()` return `GetIsShutdownRequested()`, however this is used internally so another private function instead of `GetIsRunning()`. The C API also needs to be updated.

I also mark as deprecated and change the sample to use `GetIsShutdownRequested()`. 

Since deprecated is C++14 and enkiTS is C++11 that requires a macro to only enable if the feature is present.

Since this requires a few internal changes I think I would prefer to handle most of it, but if you would like to submit a PR for switching the sample to `GetIsShutdownRequested()` and optionally the `[[deprecated]]` using an `ENKI_DEPRECATED` macro then I would accept those, but I'm also happy to do them myself.

**Comment by spnda** [comment]
I have those changes locally already so I'll just push and open, thank you.
