### ISSUE TITLE
Pin threads on CPU

### ISSUE THREAD

**Issue by nipunG314** [dougbinks/enkiTS#131]
Hi, is there a way to set the cpu affinity of the threads created by the scheduler in order to minimize the context switching cost at runtime?

I basically want thread 0 -> core 0, thread 1 -> core 1. Or does enkiTS do that automatically?

**Comment by dougbinks** [comment]
enkiTS doesn't provide a means to set the threads affinity, and in general I would advise against doing so.

Setting affinity may give you a boost to performance, but if you don't control what is run on the target machine (for example your program is being run by someone else), then another application which sets affinity could cause more context switching, and potentially significant stalls, rather than less.

For the moment you'd need to run a pinned task on each tasking thread and in that task get the thread identifier and set affinity using OS functions.

**Comment by nipunG314** [comment]
I see. I was actually planning to use enki as a basis for a game, so I don't think that should cause a problem.

If I was to create a group of empty pinned tasks for each thread, and then set the affinity, would affinity be fixed for the remainder of the program's lifetime?

**Comment by dougbinks** [comment]
> I see. I was actually planning to use enki as a basis for a game, so I don't think that should cause a problem.

If your game runs on PC and not a closed platform console then I would very much recommend not setting an affinity (enkiTS was designed for games).

> If I was to create a group of empty pinned tasks for each thread, and then set the affinity, would affinity be fixed for the remainder of the program's lifetime?

Yes, so long as you do not shutdown and restart enkiTS.
