### ISSUE TITLE
[Question] std::future

### ISSUE THREAD

**Issue by matt77hias** [dougbinks/enkiTS#27]
What is the reason for not returning a `std::future` (C++11) upon adding a task instead of having to call `WaitforTask`?

**Comment by dougbinks** [comment]
There are a number of reasons, the simplest being that I don't see any benefit in doing so.

A more complex set of reasons below:

1. Historically, enkiTS pre-dates C++11 and maintains a C++98 branch with the same API, along with a C API. Using std::future would break this.
2. Using std::future would mean including the <future> header, which would decrease the 'lightweight' nature of enkiTS and increase compile times.
3. I generally favour not using the C++ standard library in APIs since there is no guarantee you can pass std namespace objects safely between debug and release versions of code, or between different implementations.
4. Using futures would increase the memory required per task (at minimum we need to store both a pointer to the task and a pointer to the task system), which for large numbers of simple tasks could become a significant overhead.
