### ISSUE TITLE
WaitforAllAndShutdown crashes if Initialize() was not called

### ISSUE THREAD

**Issue by boxerab** [dougbinks/enkiTS#37]
Would it be useful to have an `Initialized` flag, and log warning if user tries to call methods without having initialized ?

**Comment by dougbinks** [comment]
This is a programming error, and I'd normally see a crash as a good way to inform the developer they'd made an error.

However since enkiTS has the internal state to know it's not been initialized, and since this is a rare call, I think we should treat it like delete of a null pointer and allow it to silently do nothing if it's not initialized. I'd not want to add logging as enkiTS is supposed to be lightweight.

I can add the check but might not be able to get to a computer for a few days or more.

Worth noting that enkiTS should really be initialized once at program startup, and then left. The worker threads will go to sleep and the only reason to call intialize more than once is in programs which want to vary the number of worker threads for tests.

**Comment by boxerab** [comment]
Thanks. Currently, I check the number of threads as a proxy for whether the library was initialized - if it's zero, then it was not. But, it would be nice to treat this like deleting a null pointer - return silently.

**Comment by boxerab** [comment]
In my case, I don't initialize enkiTS until I parse the command line for the number of threads desired. If parsing fails, then Initialize doesn't get called, but Shutdown is called.

**Comment by boxerab** [comment]
Perfect, thanks!
