### ISSUE TITLE
Feature Request: Shutdown

### ISSUE THREAD

**Issue by BobbyAnguelov** [dougbinks/enkiTS#84]
I dont know if this is a good idea but it was something I hit recently and can imagine it could be useful for others. Right now there doesn't exist any way to shutdown enkiTS if there are scheduled tasks.

It would be nice ot be able to call a function ("Shutdown/Exit/InsertBetterNameHere") that will wait for the currently in-flight tasks to complete and flush the queue of all remaining tasks. I've had to work around this issue by putting a global "isExitingFlag" that all tasks are checking, and then waiting for all scheduled tasks. This feels a bit dirty TBH.

Additionally, it could be useful to get a rough idea if there are still scheduled tasks. ("hasScheduledTasks, IsQueueEmpty, etc...)

**Comment by dougbinks** [comment]
The current method to shutdown enkiTS is to use `WaitforAllAndShudown()` combined with long running/looping/task generating tasks using either `GetIsRunning()` or `GetIsWaitforAllCalled` - see [API comments](https://github.com/dougbinks/enkiTS/blob/master/src/TaskScheduler.h#L315-L323).

I think having a shutdown which flushes the task queues is a good addition, though long running tasks would still need to use the above checks. Since I'm guessing this is for shutting down quickly there should be no need for special handling of TaskSets which have been started but not completed, just flush all remaining tasks. Let me know if you think otherwise.

More information about the task system is also a good idea - I have a set of advanced API additions planned including these which will expose more of the internals and allow devs to alter scheduling etc., at a slight risk of these breaking more often than the higher level APIs.

**Comment by BobbyAnguelov** [comment]
Ah okay, the "IsRunning" would be a solution for this issue but it's not really obvious since it gets set before it actually stops running. This feels rather weird for me, since it's not "running" but it is still running since tasks are being processed. Also, in my case I have lots of finite tasks scheduled and not a looping task so I guess I can still use it as a skip/early out condition. That said, this feels like something that shouldn't be pushed to the user especially for finite tasks.

This code will be weird to have at the start of every single task:

`if( !IsRunning() )
{
      return;
}`

For looping tasks, I feel would make more sense to have a more explicit call: "IsShuttingDown/IsShutdownRequested" rather than checking if "!IsRunning". For the end user and the person coming in after them, reading that will be clearer that the "!IsRunning", and it is also, IMO, more correct since the task system is technically still running, it's just that the user has asked for a manual termination of it (I think that extra context is beneficial and easier for the user to understand).

**Comment by dougbinks** [comment]
I have made an initial untested implementation in [branch dev_shutdown](https://github.com/dougbinks/enkiTS/tree/dev_shutdown).

If you can let me know if this looks like it will work for you that would be great - I intend to add an example or rework examples to use this prior to merging to main.

**Comment by BobbyAnguelov** [comment]
Changes look good and will work for me. 

I didn't realize that wait for all and shutdown was already doing that. I just assumed that "WaitForAll" was actually waiting for all tasks. I still find the waitforall vs shutdown a bit confusing, but I think I'm slowly starting to understand it. I just want to clarify my understanding. The "wait for all" flag is primarily used as a mechanism to allow the user to end looping tasks as part of normal operation? If the user wants to wait for all non-looping tasks, they need to explicitly call "WaitForTask" for all non-looping tasks?

The change works and I don't want to harp on about this too much, but I'm just wondering if flagging tasks explicitly as looping/not isn't perhaps a cleaner way to manage this aspect and can provide user control over lifetime at the scheduler level instead of at the individual task level i.e. "WaitForAllNonLoopingTasks()"/"CompleteAllLoopingTasks()/WaitForAll()". The "WaitForAll" flag coould be renamed something like "CompleteAllLoopingTasks". Anyways, this is just a thought experiment to clarify my understanding.

Super minor thing, you have a typo on ln 352 (first word).

**Comment by dougbinks** [comment]
This has now been merged into master and the dev_shutdown branch has been deleted.
